import time

import art
from art import tprint
from colorama import Fore



tprint('WebPhisher' )
time.sleep(2)

print(Fore.RED + 'Welcome to Webphiser')
print(Fore.GREEN + '[Made by: ', Fore.YELLOW + 'jescoin] ')
print(Fore.BLUE +'[v', Fore.RED + '1.0' , Fore.YELLOW + ']')

print(Fore.RED + '[+] This program will help you create phishing links!')
print(Fore.BLUE +'[?] It is like a ', Fore.RED + 'PyPhisher', Fore.BLUE +' but on Windows and Mac OS.' )

print('Choose the social network\n[1] Facebook\n[2] VK\n[3] Instagram\n[4] Twitter\n[5] Tiktok\n[6] Steam\n[7] Gmail\n[8] Github\n[9] PayPal\n[10] Netflix\n[11] Adobe\n[12] Yandex\n[13] Twitch\n[15] Reddit\n[16] Playstation\n[17] Spotify')
n = input('[?]')
if n =='1':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html#')
if n =='3':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5501/insta.html')
if n =='2':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/steam.html?')
if n =='7':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/reddit.html#')
if n =='4':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!]http://127.0.0.1:5500/twitter.html')
if n =='5':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/tiktokk.html')
if n =='8':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html#start-of-content')
if n =='6':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
if n =='9':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
if n =='10':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
if n =='11':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
if n =='12':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/indexx.html')
if n =='13':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
if n =='14':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[?] Dekstop version - http://127.0.0.1:5500/index.html\n [!] Mobile version - http://127.0.0.1:5500/mobile.html')
if n =='15':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html#/signin?entry=%2Fsignin')
if n =='16':
    print('[+] Link is  creating..')
    time.sleep(2)
    print('[+] IP-address-detect is creating... ')
    time.sleep(2)
    print('1')
    time.sleep(2)
    print('2')
    time.sleep(2)
    print('3')
    time.sleep(2)
    tprint('Link create!')
    print('[!] http://127.0.0.1:5500/index.html')
else:
    print(Fore.RED +'[-] Error! Not valid number. Try again. ')
    time.sleep(5)
    exit()